import React, { createContext, useContext, useState, useEffect } from 'react'

// 支持的语言列表
export const languages = [
  { code: 'en', name: 'English', flag: '🇺🇸', native: 'English', rtl: false },
  { code: 'zh', name: '简体中文', flag: '🇨🇳', native: '简体中文', rtl: false },
  { code: 'ko', name: '한국어', flag: '🇰🇷', native: '한국어', rtl: false },
  { code: 'ja', name: '日本語', flag: '🇯🇵', native: '日本語', rtl: false },
  { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳', native: 'Tiếng Việt', rtl: false },
  { code: 'id', name: 'Bahasa Indonesia', flag: '🇮🇩', native: 'Bahasa Indonesia', rtl: false },
  { code: 'ar', name: 'العربية', flag: '🇸🇦', native: 'العربية', rtl: true },
  { code: 'fr', name: 'Français', flag: '🇫🇷', native: 'Français', rtl: false },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪', native: 'Deutsch', rtl: false },
  { code: 'es', name: 'Español', flag: '🇪🇸', native: 'Español', rtl: false },
  { code: 'ru', name: 'Русский', flag: '🇷🇺', native: 'Русский', rtl: false },
]

// 完整翻译内容
export const translations = {
  en: {
    // 导航
    nav: {
      home: 'Home',
      products: 'Products',
      newArrivals: 'New Arrivals',
      applications: 'Applications',
      about: 'About',
      contact: 'Contact',
      getQuote: 'Get a Quote',
      byMaterial: 'By Material',
      byApplication: 'By Application',
    },
    // 首页
    home: {
      heroTitle: 'Premium Synthetic Leather Solutions',
      heroSubtitle: 'Leading manufacturer of PU leather, microfiber & specialty materials for footwear, bags, automotive & gloves',
      exploreProducts: 'Explore Products',
      requestQuote: 'Request a Quote',
      ourProducts: 'Our Products',
      productTitle: 'Premium Leather Materials',
      productDesc: 'From classic PU leather to cutting-edge microfiber and specialty series — we have the perfect material for every application.',
      certifications: 'Quality Assurance',
      certTitle: 'Certified & Trusted',
      certDesc: 'All products meet international quality and safety standards, ensuring reliability for every partner.',
      whyChooseUs: 'Why Choose Us',
      advantages: 'Our Core Advantages',
      advantagesDesc: 'With professional R&D capabilities, strict quality control, and a customer-first service philosophy, we deliver exceptional value.',
      learnMore: 'Learn More',
      readyToFind: 'Ready to Find Your Perfect Leather?',
      ctaDesc: 'Get in touch with our team for free samples, technical consultation, or a customized quote.',
      browseProducts: 'Browse Products',
    },
    // 产品页
    products: {
      title: 'Product Series',
      byMaterial: 'By Material Type',
      byMaterialDesc: 'Choose the material that best fits your product requirements.',
      byApplication: 'By Application',
      byApplicationDesc: 'Find the perfect material for your specific industry.',
      viewDetails: 'View Details',
      downloadCatalog: 'Download Catalog',
      needCustom: 'Need Custom Material?',
      needCustomDesc: 'We offer custom color matching, thickness adjustment, and functional finishes. Contact us to discuss your requirements.',
      requestSample: 'Request Custom Sample',
    },
    // 产品详情页
    productDetail: {
      backToProducts: 'Back to Products',
      productOverview: 'Product Overview',
      composition: 'Composition',
      availableColors: 'Available Colors',
      applications: 'Applications',
      technicalSpecs: 'Technical Specifications',
      downloadFullTDS: 'Download Full TDS',
      fabricInfo: 'Fabric Information',
      physical: 'Physical Properties',
      colorFastness: 'Color Fastness',
      environmental: 'Environmental & Compliance',
      thickness: 'Thickness',
      width: 'Width',
      weight: 'Weight',
      moq: 'MOQ',
      requestQuote: 'Request a Quote',
      downloadSpec: 'Download Spec Sheet',
      inquiry: 'Request a Sample or Quote',
      inquiryDesc: 'Tell us your requirements and we\'ll get back to you within 24 hours.',
      getInTouch: 'Get in Touch',
      getInTouchDesc: 'Contact our sales team for product samples, custom specifications, or detailed quotations.',
      freeSamples: 'Free Samples:',
      freeSamplesDesc: 'We offer free A4-size samples for quality evaluation. Custom samples available on request.',
      sendInquiry: 'Send Us an Inquiry',
      sendInquiryDesc: 'Fill out the form below and we\'ll get back to you shortly.',
    },
    // 询盘表单
    inquiry: {
      company: 'Company Name',
      contact: 'Contact Person',
      phone: 'Phone',
      email: 'Email',
      product: 'Product',
      thickness: 'Thickness',
      color: 'Color',
      usage: 'Usage/Purpose',
      quantity: 'Quantity Needed',
      requirements: 'Special Requirements',
      message: 'Message',
      submit: 'Submit Inquiry',
      submitting: 'Submitting...',
      success: 'Inquiry submitted successfully! We will contact you soon.',
      error: 'Failed to submit. Please try again.',
    },
    // 关于页
    about: {
      title: 'About Us',
      subtitle: 'Your Trusted Partner in Synthetic Leather',
      story: 'Our Story',
      storyDesc: 'Founded in Dongguan, China, Ultra Leather has grown to become a leading manufacturer of premium synthetic leather materials...',
      mission: 'Our Mission',
      missionDesc: 'To provide global customers with innovative, sustainable, and cost-effective synthetic leather solutions...',
      vision: 'Our Vision',
      visionDesc: 'To be the most trusted partner for synthetic leather materials worldwide...',
      team: 'Our Team',
      capabilities: 'Our Capabilities',
    },
    // 联系页
    contact: {
      title: 'Contact Us',
      subtitle: 'Get in Touch',
      name: 'Full Name',
      email: 'Email Address',
      subject: 'Subject',
      message: 'Your Message',
      send: 'Send Message',
      sending: 'Sending...',
      success: 'Message sent successfully! We will reply soon.',
      company: 'Company Name',
      address: 'Address',
      phone: 'Phone',
      whatsapp: 'WhatsApp',
      hours: 'Business Hours',
    },
    // 页脚
    footer: {
      company: 'Ultra Leather',
      tagline: 'Premium Synthetic Leather Solutions',
      products: 'Products',
      company: 'Company',
      contact: 'Contact',
      newsletter: 'Newsletter',
      newsletterDesc: 'Subscribe to get the latest updates.',
      rights: 'All rights reserved.',
    },
    // 通用
    common: {
      loading: 'Loading...',
      error: 'Error',
      retry: 'Retry',
      close: 'Close',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      add: 'Add',
      search: 'Search',
      noResults: 'No results found',
      learnMore: 'Learn More',
      viewAll: 'View All',
    },
  },
  zh: {
    nav: {
      home: '首页',
      products: '产品',
      newArrivals: '新品上市',
      applications: '应用领域',
      about: '关于我们',
      contact: '联系我们',
      getQuote: '获取报价',
      byMaterial: '按材料',
      byApplication: '按应用',
    },
    home: {
      heroTitle: '高端人造革解决方案',
      heroSubtitle: '专业生产PU皮革、超细纤维及特种材料，广泛应用于鞋材、箱包、汽车内饰和专业手套领域',
      exploreProducts: '浏览产品',
      requestQuote: '获取报价',
      ourProducts: '我们的产品',
      productTitle: '优质皮革材料',
      productDesc: '从经典PU皮革到前沿的超细纤维和特种系列——我们为每个应用领域提供完美材料。',
      certifications: '品质保证',
      certTitle: '认证与信赖',
      certDesc: '所有产品均符合国际质量和安全标准，确保每位合作伙伴的可靠性。',
      whyChooseUs: '为什么选择我们',
      advantages: '我们的核心优势',
      advantagesDesc: '凭借专业的研发能力、严格的质量控制和以客户为中心的服务理念，我们为全球合作伙伴创造卓越价值。',
      learnMore: '了解更多',
      readyToFind: '准备好找到完美皮革了吗？',
      ctaDesc: '联系我们团队，获取免费样品、技术咨询或定制报价。',
      browseProducts: '浏览产品',
    },
    products: {
      title: '产品系列',
      byMaterial: '按材料类型',
      byMaterialDesc: '选择最适合您产品需求的材料。',
      byApplication: '按应用领域',
      byApplicationDesc: '为您的特定行业寻找完美材料。',
      viewDetails: '查看详情',
      downloadCatalog: '下载产品册',
      needCustom: '需要定制材料？',
      needCustomDesc: '我们提供定制配色、厚度调整和功能整理。联系我们讨论您的具体要求。',
      requestSample: '申请定制样品',
    },
    productDetail: {
      backToProducts: '返回产品',
      productOverview: '产品概述',
      composition: '成分',
      availableColors: '可选颜色',
      applications: '应用领域',
      technicalSpecs: '技术规格',
      downloadFullTDS: '下载完整技术资料',
      fabricInfo: '面料信息',
      physical: '物理性能',
      colorFastness: '色牢度',
      environmental: '环境与合规',
      thickness: '厚度',
      width: '宽度',
      weight: '克重',
      moq: '最小起订量',
      requestQuote: '申请报价',
      downloadSpec: '下载规格表',
      inquiry: '申请样品或报价',
      inquiryDesc: '告诉我们您的需求，我们将在24小时内回复。',
      getInTouch: '联系我们',
      getInTouchDesc: '联系我们的销售团队，获取产品样品、定制规格或详细报价。',
      freeSamples: '免费样品：',
      freeSamplesDesc: '我们提供免费A4尺寸样品供质量评估。也可按要求提供定制样品。',
      sendInquiry: '发送询盘',
      sendInquiryDesc: '填写下方表单，我们将在最短时间内回复您。',
    },
    inquiry: {
      company: '公司名称',
      contact: '联系人',
      phone: '电话',
      email: '邮箱',
      product: '产品',
      thickness: '厚度',
      color: '颜色',
      usage: '用途',
      quantity: '需求数量',
      requirements: '特殊要求',
      message: '留言',
      submit: '提交询盘',
      submitting: '提交中...',
      success: '询盘提交成功！我们将尽快与您联系。',
      error: '提交失败，请重试。',
    },
    about: {
      title: '关于我们',
      subtitle: '您值得信赖的人造革合作伙伴',
      story: '我们的故事',
      storyDesc: '澳丽德新材料有限公司成立于中国东莞，已发展成为优质人造革材料的领先制造商...',
      mission: '我们的使命',
      missionDesc: '为全球客户提供创新、可持续且性价比高的人造革解决方案...',
      vision: '我们的愿景',
      visionDesc: '成为全球最值得信赖的人造革材料合作伙伴...',
      team: '我们的团队',
      capabilities: '我们的能力',
    },
    contact: {
      title: '联系我们',
      subtitle: '获取联系方式',
      name: '姓名',
      email: '电子邮箱',
      subject: '主题',
      message: '您的留言',
      send: '发送消息',
      sending: '发送中...',
      success: '消息发送成功！我们将尽快回复。',
      company: '公司名称',
      address: '地址',
      phone: '电话',
      whatsapp: 'WhatsApp',
      hours: '营业时间',
    },
    footer: {
      company: '澳丽德',
      tagline: '优质人造革解决方案',
      products: '产品',
      company: '公司',
      contact: '联系',
      newsletter: '订阅资讯',
      newsletterDesc: '订阅以获取最新动态。',
      rights: '版权所有。',
    },
    common: {
      loading: '加载中...',
      error: '错误',
      retry: '重试',
      close: '关闭',
      save: '保存',
      cancel: '取消',
      delete: '删除',
      edit: '编辑',
      add: '添加',
      search: '搜索',
      noResults: '未找到结果',
      learnMore: '了解更多',
      viewAll: '查看全部',
    },
  },
  ko: {
    nav: {
      home: '홈',
      products: '제품',
      newArrivals: '신제품',
      applications: '적용 분야',
      about: '회사 소개',
      contact: '문의',
      getQuote: '견적 요청',
      byMaterial: '소재별',
      byApplication: '용도별',
    },
    home: {
      heroTitle: '고급 합성 가죽 솔루션',
      heroSubtitle: '신발, 가방, 자동차 내장재 및 장갑용 PU 가죽, 마이크로파이버 및 특수 소재 전문 제조업체',
      exploreProducts: '제품 보기',
      requestQuote: '견적 요청',
      ourProducts: '우리 제품',
      productTitle: '프리미엄 가죽 소재',
      productDesc: '클래식 PU 가죽에서 최첨단 마이크로파이버 및 특수 시리즈까지 - 모든 적용 분야에 완벽한 소재를 제공합니다.',
      certifications: '품질보증',
      certTitle: '인증 및 신뢰',
      certDesc: '모든 제품은 국제 품질 및 안전 표준을 충족하여 모든 파트너의 신뢰성을 보장합니다.',
      whyChooseUs: '왜 우리를 선택하나요',
      advantages: '핵심 우위',
      advantagesDesc: '전문적인 R&D 역량, 엄격한 품질 관리 및 고객 중심 서비스 철학으로 뛰어난 가치를 제공합니다.',
      learnMore: '자세히 보기',
      readyToFind: '완벽한 가죽을 찾을 준비가 되셨나요?',
      ctaDesc: '무료 샘플, 기술 상담 또는 맞춤형 견적을 위해 당사 팀에 문의하세요.',
      browseProducts: '제품 둘러보기',
    },
    products: {
      title: '제품 시리즈',
      byMaterial: '소재별',
      byMaterialDesc: '제품 요구 사항에 가장 적합한 소재를 선택하세요.',
      byApplication: '용도별',
      byApplicationDesc: '특정 업종에 적합한 완벽한 소재를 찾으세요.',
      viewDetails: '자세히 보기',
      downloadCatalog: '카탈로그 다운로드',
      needCustom: '맞춤 소재가 필요하신가요?',
      needCustomDesc: '맞춤 색상, 두께 조정 및 기능성 옵션을 제공합니다.요구사항에 대해 문의하세요.',
      requestSample: '맞춤 샘플 요청',
    },
    productDetail: {
      backToProducts: '제품으로 돌아가기',
      productOverview: '제품 개요',
      composition: '구성',
      availableColors: '사용 가능한 색상',
      applications: '적용 분야',
      technicalSpecs: '기술 사양',
      downloadFullTDS: '전체 TDS 다운로드',
      fabricInfo: '원단 정보',
      physical: '물리적 특성',
      colorFastness: '색상 견뢰도',
      environmental: '환경 및 적합성',
      thickness: '두께',
      width: '폭',
      weight: '중량',
      moq: '최소 주문량',
      requestQuote: '견적 요청',
      downloadSpec: '사양서 다운로드',
      inquiry: '샘플 또는 견적 요청',
      inquiryDesc: '요구사항을 알려주시면 24시간 이내에 회신드리겠습니다.',
      getInTouch: '문의하기',
      getInTouchDesc: '제품 샘플, 맞춤형 사양 또는 상세 견적을 위해 영업팀에 문의하세요.',
      freeSamples: '무료 샘플:',
      freeSamplesDesc: '품질 평가를 위한 무료 A4 사이즈 샘플을 제공합니다.맞춤 샘플도 요청 가능합니다.',
      sendInquiry: '문의 보내기',
      sendInquiryDesc: '아래 양식을 작성해 주시면 곧 회신드리겠습니다.',
    },
    inquiry: {
      company: '회사명',
      contact: '담당자',
      phone: '전화',
      email: '이메일',
      product: '제품',
      thickness: '두께',
      color: '색상',
      usage: '용도',
      quantity: '필요 수량',
      requirements: '특별 요구사항',
      message: '메시지',
      submit: '문의 제출',
      submitting: '제출 중...',
      success: '문의가 성공적으로 제출되었습니다!곧 연락드리겠습니다.',
      error: '제출에 실패했습니다.다시 시도해 주세요.',
    },
    about: {
      title: '회사 소개',
      subtitle: '합성 가죽 분야의 신뢰받는 파트너',
      story: '우리의 이야기',
      storyDesc: '중국의 동관에 설립된 Ultra Leather는 프리미엄 합성 가죽 소재의 주요 제조업체로 성장했습니다...',
      mission: '우리의 사명',
      missionDesc: '혁신적이고 지속 가능하며 비용 효율적인 합성 가죽 솔루션을 전 세계 고객에게 제공합니다...',
      vision: '우리의 비전',
      visionDesc: '전 세계에서 가장 신뢰받는 합성 가죽 소재 파트너가 되는 것...',
      team: '우리 팀',
      capabilities: '우리의 역량',
    },
    contact: {
      title: '문의하기',
      subtitle: '연락처',
      name: '성명',
      email: '이메일 주소',
      subject: '제목',
      message: '메시지',
      send: '메시지 보내기',
      sending: '보내는 중...',
      success: '메시지가 성공적으로 전송되었습니다!곧 회신드리겠습니다.',
      company: '회사명',
      address: '주소',
      phone: '전화',
      whatsapp: 'WhatsApp',
      hours: '영업 시간',
    },
    footer: {
      company: '울트라 레더',
      tagline: '프리미엄 합성 가죽 솔루션',
      products: '제품',
      company: '회사',
      contact: '문의',
      newsletter: '뉴스레터',
      newsletterDesc: '최신 업데이트를 받으려면 구독하세요.',
      rights: '모든 권리 보유.',
    },
    common: {
      loading: '로딩 중...',
      error: '오류',
      retry: '재시도',
      close: '닫기',
      save: '저장',
      cancel: '취소',
      delete: '삭제',
      edit: '편집',
      add: '추가',
      search: '검색',
      noResults: '결과 없음',
      learnMore: '자세히 보기',
      viewAll: '전체 보기',
    },
  },
  ja: {
    nav: {
      home: 'ホーム',
      products: '製品',
      newArrivals: '新製品',
      applications: '用途',
      about: '会社概要',
      contact: 'お問い合わせ',
      getQuote: '見積もり',
      byMaterial: '素材別',
      byApplication: '用途別',
    },
    home: {
      heroTitle: '高級合成皮革ソリューション',
      heroSubtitle: '靴、バッグ、航空内幕装、手袋向けのPUレザー、マイクロファイバー、特殊素材の専門メーカー',
      exploreProducts: '製品を見る',
      requestQuote: '見積もりを依頼',
      ourProducts: '製品紹介',
      productTitle: 'プレミアムレザー素材',
      productDesc: 'クラシックなPUレザーから最先端のマイクロファイバーまで、すべての用途に最適な素材を提供します。',
      certifications: '品質保証',
      certTitle: '認証と信頼',
      certDesc: 'すべての製品は国際的な品質・安全基準を満たし、すべてのパートナーへの信頼性を確保します。',
      whyChooseUs: 'なぜ私たちを選んだのですか',
      advantages: '私たちのコア优势',
      advantagesDesc: '専門的な研究開発能力、厳格な品質管理、カスタマーサービスの философиーで優秀な価値を提供します。',
      learnMore: '詳細を見る',
      readyToFind: '完璧なレザーを見つける準備ができましたか？',
      ctaDesc: '無料サンプル、技術コンサルタント、カスタマイズ見積もりについては、お気軽にお問い合わせください。',
      browseProducts: '製品を閲覧',
    },
    products: {
      title: '製品シリーズ',
      byMaterial: '素材別',
      byMaterialDesc: '製品の要件に最適な素材を選んでください。',
      byApplication: '用途別',
      byApplicationDesc: '特定の業界にぴったりの素材を見つけましょう。',
      viewDetails: '詳細を見る',
      downloadCatalog: 'カタログをダウンロード',
      needCustom: 'カスタム素材が必要ですか？',
      needCustomDesc: 'カスタム配色、厚さ調整、機能仕上げを提供します。要件についてはご連絡ください。',
      requestSample: 'カスタムサンプルをリクエスト',
    },
    productDetail: {
      backToProducts: '製品に戻る',
      productOverview: '製品概要',
      composition: '組成',
      availableColors: '利用可能な色',
      applications: '用途',
      technicalSpecs: '技術仕様',
      downloadFullTDS: '完全なTDSをダウンロード',
      fabricInfo: '布料情報',
      physical: '物理的性質',
      colorFastness: '染色堅牢度',
      environmental: '環境コンプライアンス',
      thickness: '厚さ',
      width: '幅',
      weight: '重量',
      moq: '最小注文数',
      requestQuote: '見積もりを依頼',
      downloadSpec: '仕様シートをダウンロード',
      inquiry: 'サンプルまたは見積もりをリクエスト',
      inquiryDesc: '要件をお聞かせいただければ、24時間以内にご連絡いたします。',
      getInTouch: 'お問い合わせ',
      getInTouchDesc: '製品サンプル、カスタム仕様、詳細な見積もりについては営業チームにお問い合わせください。',
      freeSamples: '無料サンプル：',
      freeSamplesDesc: '品質評価用の無料A4サイズサンプルを提供しています。カスタムサンプルもご依頼いただけます。',
      sendInquiry: 'お問い合わせを送信',
      sendInquiryDesc: '以下のフォームにご記入いただければ、折返しご連絡いたします。',
    },
    inquiry: {
      company: '会社名',
      contact: '担当者',
      phone: '電話番号',
      email: 'メール',
      product: '製品',
      thickness: '厚さ',
      color: '色',
      usage: '用途',
      quantity: '必要数量',
      requirements: '特別な要件',
      message: 'メッセージ',
      submit: 'お問い合わせを送信',
      submitting: '送信中...',
      success: 'お問い合わせが正常に送信されました！まもなくご連絡いたします。',
      error: '送信に失敗しました。もう一度お試しください。',
    },
    about: {
      title: '会社概要',
      subtitle: '合成皮革の信頼できるパートナー',
      story: '私たちのストーリー',
      storyDesc: '中国東莞に設立されたUltra Leatherは、高品質合成皮革素材の大手メーカーとして成長しました...',
      mission: '私たちの使命',
      missionDesc: '革新的で持続可能かつコスト效益的な合成皮革ソリューションを世界の顧客に提供すること...',
      vision: '私たちのビジョン',
      visionDesc: '世界の合成皮革素材において最も信頼されるパートナーになること...',
      team: '私たちのチーム',
      capabilities: '私たちの強み',
    },
    contact: {
      title: 'お問い合わせ',
      subtitle: 'ご連絡ください',
      name: 'お名前',
      email: 'メールアドレス',
      subject: '件名',
      message: 'メッセージ',
      send: 'メッセージを送信',
      sending: '送信中...',
      success: 'メッセージが正常に送信されました！まもなくり返事いたします。',
      company: '会社名',
      address: '住所',
      phone: '電話',
      whatsapp: 'WhatsApp',
      hours: '営業時間',
    },
    footer: {
      company: 'ウルトラレザー',
      tagline: 'プレミアム合成皮革ソリューション',
      products: '製品',
      company: '会社',
      contact: 'お問い合わせ',
      newsletter: 'ニュースレター',
      newsletterDesc: '最新情報を入手するには購読してください。',
      rights: '全著作権所有.',
    },
    common: {
      loading: '読み込み中...',
      error: 'エラー',
      retry: '再試行',
      close: '閉じる',
      save: '保存',
      cancel: 'キャンセル',
      delete: '削除',
      edit: '編集',
      add: '追加',
      search: '検索',
      noResults: '結果なし',
      learnMore: '詳細を見る',
      viewAll: 'すべて表示',
    },
  },
  vi: {
    nav: {
      home: 'Trang chủ',
      products: 'Sản phẩm',
      newArrivals: 'Sản phẩm mới',
      applications: 'Ứng dụng',
      about: 'Giới thiệu',
      contact: 'Liên hệ',
      getQuote: 'Báo giá',
      byMaterial: 'Theo chất liệu',
      byApplication: 'Theo ứng dụng',
    },
    home: {
      heroTitle: 'Giải pháp Da tổng hợp cao cấp',
      heroSubtitle: 'Nhà sản xuất chuyên nghiệp PU da, sợi siêu nhỏ và vật liệu đặc biệt cho giày, túi, nội thất ô tô và găng tay',
      exploreProducts: 'Xem sản phẩm',
      requestQuote: 'Yêu cầu báo giá',
      ourProducts: 'Sản phẩm của chúng tôi',
      productTitle: 'Vật liệu da cao cấp',
      productDesc: 'Từ PU da cổ điển đến sợi siêu nhỏ tiên tiến - chúng tôi có vật liệu hoàn hảo cho mọi ứng dụng.',
      certifications: 'Đảm bảo chất lượng',
      certTitle: 'Chứng nhận & Tin cậy',
      certDesc: 'Tất cả sản phẩm đều đáp ứng tiêu chuẩn chất lượng và an toàn quốc tế.',
      whyChooseUs: 'Tại sao chọn chúng tôi',
      advantages: 'Lợi thế cốt lõi',
      advantagesDesc: 'Với năng lực R&D chuyên nghiệp, kiểm soát chất lượng nghiêm ngặt, chúng tôi mang đến giá trị vượt trội.',
      learnMore: 'Tìm hiểu thêm',
      readyToFind: 'Sẵn sàng tìm da hoàn hảo?',
      ctaDesc: 'Liên hệ đội ngũ để nhận mẫu miễn phí, tư vấn kỹ thuật hoặc báo giá tùy chỉnh.',
      browseProducts: 'Xem sản phẩm',
    },
    products: {
      title: 'Dòng sản phẩm',
      byMaterial: 'Theo chất liệu',
      byMaterialDesc: 'Chọn chất liệu phù hợp nhất với yêu cầu sản phẩm của bạn.',
      byApplication: 'Theo ứng dụng',
      byApplicationDesc: 'Tìm chất liệu hoàn hảo cho ngành cụ thể của bạn.',
      viewDetails: 'Xem chi tiết',
      downloadCatalog: 'Tải catalog',
      needCustom: 'Cần vật liệu tùy chỉnh?',
      needCustomDesc: 'Chúng tôi cung cấp màu sắc, độ dày và hoàn thiện chức năng tùy chỉnh.',
      requestSample: 'Yêu cầu mẫu tùy chỉnh',
    },
    productDetail: {
      backToProducts: ' Quay lại sản phẩm',
      productOverview: 'Tổng quan sản phẩm',
      composition: 'Thành phần',
      availableColors: 'Màu sắc có sẵn',
      applications: 'Ứng dụng',
      technicalSpecs: 'Thông số kỹ thuật',
      downloadFullTDS: 'Tải TDS đầy đủ',
      fabricInfo: 'Thông tin vải',
      physical: 'Tính chất vật lý',
      colorFastness: 'Độ bền màu',
      environmental: 'Môi trường & Tuân thủ',
      thickness: 'Độ dày',
      width: 'Chiều rộng',
      weight: 'Trọng lượng',
      moq: 'MOQ',
      requestQuote: 'Yêu cầu báo giá',
      downloadSpec: 'Tải bảng thông số',
      inquiry: 'Yêu cầu mẫu hoặc báo giá',
      inquiryDesc: 'Chia sẻ yêu cầu của bạn, chúng tôi sẽ phản hồi trong 24 giờ.',
      getInTouch: 'Liên hệ',
      getInTouchDesc: 'Liên hệ đội ngũ bán hàng để được mẫu, thông số tùy chỉnh hoặc báo giá chi tiết.',
      freeSamples: 'Mẫu miễn phí:',
      freeSamplesDesc: 'Chúng tôi cung cấp mẫu A4 miễn phí để đánh giá chất lượng.',
      sendInquiry: 'Gửi yêu cầu',
      sendInquiryDesc: 'Điền form bên dưới, chúng tôi sẽ phản hồi sớm nhất.',
    },
    inquiry: {
      company: 'Tên công ty',
      contact: 'Người liên hệ',
      phone: 'Điện thoại',
      email: 'Email',
      product: 'Sản phẩm',
      thickness: 'Độ dày',
      color: 'Màu sắc',
      usage: 'Mục đích sử dụng',
      quantity: 'Số lượng cần',
      requirements: 'Yêu cầu đặc biệt',
      message: 'Tin nhắn',
      submit: 'Gửi yêu cầu',
      submitting: 'Đang gửi...',
      success: 'Gửi thành công! Chúng tôi sẽ liên hệ sớm.',
      error: 'Gửi thất bại. Vui lòng thử lại.',
    },
    about: {
      title: 'Giới thiệu',
      subtitle: 'Đối tác đáng tin cậy về da tổng hợp',
      story: 'Câu chuyện của chúng tôi',
      storyDesc: 'Được thành lập tại Dongguan, Trung Quốc, Ultra Leather đã phát triển thành nhà sản xuất hàng đầu...',
      mission: 'Sứ mệnh',
      missionDesc: 'Cung cấp giải pháp da tổng hợp sáng tạo, bền vững cho khách hàng toàn cầu...',
      vision: 'Tầm nhìn',
      visionDesc: 'Trở thành đối tác đáng tin cậy nhất về vật liệu da tổng hợp trên toàn thế giới...',
      team: 'Đội ngũ',
      capabilities: 'Năng lực',
    },
    contact: {
      title: 'Liên hệ',
      subtitle: 'Kết nối với chúng tôi',
      name: 'Họ và tên',
      email: 'Email',
      subject: 'Chủ đề',
      message: 'Tin nhắn',
      send: 'Gửi tin nhắn',
      sending: 'Đang gửi...',
      success: 'Gửi thành công! Chúng tôi sẽ phản hồi sớm.',
      company: 'Tên công ty',
      address: 'Địa chỉ',
      phone: 'Điện thoại',
      whatsapp: 'WhatsApp',
      hours: 'Giờ làm việc',
    },
    footer: {
      company: 'Ultra Leather',
      tagline: 'Giải pháp da tổng hợp cao cấp',
      products: 'Sản phẩm',
      company: 'Công ty',
      contact: 'Liên hệ',
      newsletter: 'Bản tin',
      newsletterDesc: 'Đăng ký để nhận cập nhật mới nhất.',
      rights: 'Mọi quyền được bảo lưu.',
    },
    common: {
      loading: 'Đang tải...',
      error: 'Lỗi',
      retry: 'Thử lại',
      close: 'Đóng',
      save: 'Lưu',
      cancel: 'Hủy',
      delete: 'Xóa',
      edit: 'Sửa',
      add: 'Thêm',
      search: 'Tìm kiếm',
      noResults: 'Không tìm thấy',
      learnMore: 'Tìm hiểu thêm',
      viewAll: 'Xem tất cả',
    },
  },
  id: {
    nav: {
      home: 'Beranda',
      products: 'Produk',
      newArrivals: 'Produk Baru',
      applications: 'Aplikasi',
      about: 'Tentang',
      contact: 'Kontak',
      getQuote: 'Minta Penawaran',
      byMaterial: 'Berdasarkan Bahan',
      byApplication: 'Berdasarkan Aplikasi',
    },
    home: {
      heroTitle: 'Solusi Kulit Sintetis Premium',
      heroSubtitle: 'Produsen profesional PU kulit, microfiber dan bahan khusus untuk sepatu, tas, interior otomotif dan sarung tangan',
      exploreProducts: 'Lihat Produk',
      requestQuote: 'Minta Penawaran',
      ourProducts: 'Produk Kami',
      productTitle: 'Bahan Kulit Premium',
      productDesc: 'Dari PU kulit klasik hingga microfiber canggih - kami memiliki bahan sempurna untuk setiap aplikasi.',
      certifications: 'Jaminan Kualitas',
      certTitle: 'Sertifikasi & Terpercaya',
      certDesc: 'Semua produk memenuhi standar kualitas dan keamanan internasional.',
      whyChooseUs: 'Mengapa Memilih Kami',
      advantages: 'Keunggulan Inti',
      advantagesDesc: 'Dengan kemampuan R&D profesional dan kontrol kualitas ketat, kami memberikan nilai exceptional.',
      learnMore: 'Pelajari Lebih',
      readyToFind: 'Siap Menemukan Kulit Sempurna?',
      ctaDesc: 'Hubungi tim kami untuk sampel gratis, konsultasi teknis atau penawaran khusus.',
      browseProducts: 'Jelajahi Produk',
    },
    products: {
      title: 'Seri Produk',
      byMaterial: 'Berdasarkan Bahan',
      byMaterialDesc: 'Pilih bahan yang paling sesuai dengan kebutuhan produk Anda.',
      byApplication: 'Berdasarkan Aplikasi',
      byApplicationDesc: 'Temukan bahan sempurna untuk industri spesifik Anda.',
      viewDetails: 'Lihat Detail',
      downloadCatalog: 'Unduh Katalog',
      needCustom: 'Butuh Bahan Kustom?',
      needCustomDesc: 'Kami menawarkan pewarnaan kustom, penyesuaian ketebalan, dan finishing fungsional.',
      requestSample: 'Minta Sampel Kustom',
    },
    productDetail: {
      backToProducts: 'Kembali ke Produk',
      productOverview: 'Ringkasan Produk',
      composition: 'Komposisi',
      availableColors: 'Warna Tersedia',
      applications: 'Aplikasi',
      technicalSpecs: 'Spesifikasi Teknis',
      downloadFullTDS: 'Unduh TDS Lengkap',
      fabricInfo: 'Info Kain',
      physical: 'Properti Fisik',
      colorFastness: 'Ketahanan Warna',
      environmental: 'Lingkungan & Kepatuhan',
      thickness: 'Ketebalan',
      width: 'Lebar',
      weight: 'Berat',
      moq: 'MOQ',
      requestQuote: 'Minta Penawaran',
      downloadSpec: 'Unduh Lembar Spesifikasi',
      inquiry: 'Minta Sampel atau Penawaran',
      inquiryDesc: 'Ceritakan kebutuhan Anda, kami akan merespons dalam 24 jam.',
      getInTouch: 'Hubungi Kami',
      getInTouchDesc: 'Hubungi tim penjualan untuk sampel produk, spesifikasi kustom, atau penawaran detail.',
      freeSamples: 'Sampel Gratis:',
      freeSamplesDesc: 'Kami menawarkan sampel ukuran A4 gratis untuk evaluasi kualitas.',
      sendInquiry: 'Kirim Permintaan',
      sendInquiryDesc: 'Isi formulir di bawah dan kami akan segera menghubungi Anda.',
    },
    inquiry: {
      company: 'Nama Perusahaan',
      contact: 'Orang Kontak',
      phone: 'Telepon',
      email: 'Email',
      product: 'Produk',
      thickness: 'Ketebalan',
      color: 'Warna',
      usage: 'Penggunaan',
      quantity: 'Jumlah Dibutuhkan',
      requirements: 'Persyaratan Khusus',
      message: 'Pesan',
      submit: 'Kirim Permintaan',
      submitting: 'Mengirim...',
      success: 'Permintaan berhasil dikirim! Kami akan segera menghubungi.',
      error: 'Gagal mengirim. Silakan coba lagi.',
    },
    about: {
      title: 'Tentang Kami',
      subtitle: 'Partner Terpercaya dalam Kulit Sintetis',
      story: 'Cerita Kami',
      storyDesc: 'Didirikan di Dongguan, China, Ultra Leather telah berkembang menjadi produsen utama...',
      mission: 'Misi Kami',
      missionDesc: 'Memberikan solusi kulit sintetis yang inovatif dan berkelanjutan...',
      vision: 'Visi Kami',
      visionDesc: 'Menjadi partner paling terpercaya untuk bahan kulit sintetis di seluruh dunia...',
      team: 'Tim Kami',
      capabilities: 'Kemampuan Kami',
    },
    contact: {
      title: 'Kontak Kami',
      subtitle: 'Hubungi Kami',
      name: 'Nama Lengkap',
      email: 'Alamat Email',
      subject: 'Subjek',
      message: 'Pesan Anda',
      send: 'Kirim Pesan',
      sending: 'Mengirim...',
      success: 'Pesan berhasil dikirim! Kami akan segera membalas.',
      company: 'Nama Perusahaan',
      address: 'Alamat',
      phone: 'Telepon',
      whatsapp: 'WhatsApp',
      hours: 'Jam Kerja',
    },
    footer: {
      company: 'Ultra Leather',
      tagline: 'Solusi Kulit Sintetis Premium',
      products: 'Produk',
      company: 'Perusahaan',
      contact: 'Kontak',
      newsletter: 'Buletin',
      newsletterDesc: 'Berlangganan untuk update terbaru.',
      rights: 'Hak cipta dilindungi.',
    },
    common: {
      loading: 'Memuat...',
      error: 'Kesalahan',
      retry: 'Coba lagi',
      close: 'Tutup',
      save: 'Simpan',
      cancel: 'Batal',
      delete: 'Hapus',
      edit: 'Edit',
      add: 'Tambah',
      search: 'Cari',
      noResults: 'Tidak ada hasil',
      learnMore: 'Pelajari Lebih',
      viewAll: 'Lihat Semua',
    },
  },
  ar: {
    nav: {
      home: 'الرئيسية',
      products: 'المنتجات',
      newArrivals: 'وصل حديثاً',
      applications: 'التطبيقات',
      about: 'عن الشركة',
      contact: 'اتصل بنا',
      getQuote: 'احصل على عرض سعر',
      byMaterial: 'حسب المادة',
      byApplication: 'حسب التطبيق',
    },
    home: {
      heroTitle: 'حلول الجلد الصناعي الفاخر',
      heroSubtitle: 'مصنع محترف للجلد PU والألياف الدقيقة والمواد الخاصة للأحذية والحقائب وتجهيزات السيارات والقفازات',
      exploreProducts: 'عرض المنتجات',
      requestQuote: 'طلب عرض سعر',
      ourProducts: 'منتجاتنا',
      productTitle: 'مواد الجلد الفاخرة',
      productDesc: 'من الجلد PU الكلاسيكي إلى الألياف الدقيقة المتقدمة - لدينا المادة المثالية لكل تطبيق.',
      certifications: 'ضمان الجودة',
      certTitle: 'معتمدون وموثوقون',
      certDesc: 'جميع المنتجات تلبي معايير الجودة والسلامة الدولية.',
      whyChooseUs: 'لماذا نحن',
      advantages: 'مزايانا الأساسية',
      advantagesDesc: 'مع قدرات البحث والتطوير الاحترافية والسيطرة الصارمة على الجودة، نقدم قيمة استثنائية.',
      learnMore: 'اعرف المزيد',
      readyToFind: 'هل أنت مستعد للعثور على الجلد المثالي؟',
      ctaDesc: 'تواصل مع فريقنا للحصول على عينات مجانية واستشارة تقنية وعروض أسعار مخصصة.',
      browseProducts: 'تصفح المنتجات',
    },
    products: {
      title: 'سلسلة المنتجات',
      byMaterial: 'حسب المادة',
      byMaterialDesc: 'اختر المادة الأنسب لمتطلبات منتجك.',
      byApplication: 'حسب التطبيق',
      byApplicationDesc: 'اعثر على المادة المثالية لقطاعك المحدد.',
      viewDetails: 'عرض التفاصيل',
      downloadCatalog: 'تحميل الكتالوج',
      needCustom: 'تحتاج مادة مخصصة؟',
      needCustomDesc: 'نقدم ألوان مخصصة وتعديل السُمك والتشطيبات الوظيفية.',
      requestSample: 'طلب عينة مخصصة',
    },
    productDetail: {
      backToProducts: 'العودة إلى المنتجات',
      productOverview: 'نظرة عامة على المنتج',
      composition: 'التكوين',
      availableColors: 'الألوان المتاحة',
      applications: 'التطبيقات',
      technicalSpecs: 'المواصفات التقنية',
      downloadFullTDS: 'تحميل TDS كامل',
      fabricInfo: 'معلومات القماش',
      physical: 'الخصائص الفيزيائية',
      colorFastness: 'ثبات اللون',
      environmental: 'البيئة والامتثال',
      thickness: 'السُمك',
      width: 'العرض',
      weight: 'الوزن',
      moq: 'الحد الأدنى للطلب',
      requestQuote: 'طلب عرض سعر',
      downloadSpec: 'تحميل ورقة المواصفات',
      inquiry: 'طلب عينة أو عرض سعر',
      inquiryDesc: 'أخبرنا بمتطلباتك وسنرد خلال 24 ساعة.',
      getInTouch: 'تواصل معنا',
      getInTouchDesc: 'تواصل مع فريق المبيعات للحصول على عينات المنتجات والمواصفات المخصصة.',
      freeSamples: 'عينات مجانية:',
      freeSamplesDesc: 'نقدم عينات بحجم A4 مجانية لتقييم الجودة.',
      sendInquiry: 'إرسال الاستفسار',
      sendInquiryDesc: 'املأ النموذج أدناه وسنتواصل معك قريباً.',
    },
    inquiry: {
      company: 'اسم الشركة',
      contact: 'الشخص المسؤول',
      phone: 'الهاتف',
      email: 'البريد الإلكتروني',
      product: 'المنتج',
      thickness: 'السُمك',
      color: 'اللون',
      usage: 'الاستخدام',
      quantity: 'الكمية المطلوبة',
      requirements: 'المتطلبات الخاصة',
      message: 'الرسالة',
      submit: 'إرسال الاستفسار',
      submitting: 'جار الإرسال...',
      success: 'تم إرسال الاستفسار بنجاح! سنتواصل معك قريباً.',
      error: 'فشل الإرسال. يرجى المحاولة مرة أخرى.',
    },
    about: {
      title: 'عن الشركة',
      subtitle: 'شريكك الموثوق في الجلد الصناعي',
      story: 'قصتنا',
      storyDesc: 'تأسست Ultra Leather في دونغقوان بالصين وأصبحت شركة رائدة في تصنيع مواد الجلد الصناعي الفاخرة...',
      mission: 'مهمتنا',
      missionDesc: 'تقديم حلول جلدية صناعية مبتكرة ومستدامة لعملائنا حول العالم...',
      vision: 'رؤيتنا',
      visionDesc: 'أن نكون الشريك الأكثر موثوقية لمواد الجلد الصناعي في جميع أنحاء العالم...',
      team: 'فريقنا',
      capabilities: 'قدراتنا',
    },
    contact: {
      title: 'اتصل بنا',
      subtitle: 'تواصل معنا',
      name: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      subject: 'الموضوع',
      message: 'رسالتك',
      send: 'إرسال الرسالة',
      sending: 'جار الإرسال...',
      success: 'تم إرسال الرسالة بنجاح! سنرد قريباً.',
      company: 'اسم الشركة',
      address: 'العنوان',
      phone: 'الهاتف',
      whatsapp: 'WhatsApp',
      hours: 'ساعات العمل',
    },
    footer: {
      company: 'ألترا ليذر',
      tagline: 'حلول الجلد الصناعي الفاخر',
      products: 'المنتجات',
      company: 'الشركة',
      contact: 'اتصل',
      newsletter: 'النشرة الإخبارية',
      newsletterDesc: 'اشترك للحصول على آخر التحديثات.',
      rights: 'جميع الحقوق محفوظة.',
    },
    common: {
      loading: 'جار التحميل...',
      error: 'خطأ',
      retry: 'إعادة المحاولة',
      close: 'إغلاق',
      save: 'حفظ',
      cancel: 'إلغاء',
      delete: 'حذف',
      edit: 'تعديل',
      add: 'إضافة',
      search: 'بحث',
      noResults: 'لا توجد نتائج',
      learnMore: 'اعرف المزيد',
      viewAll: 'عرض الكل',
    },
  },
  fr: {
    nav: {
      home: 'Accueil',
      products: 'Produits',
      newArrivals: 'Nouveautés',
      applications: 'Applications',
      about: 'À propos',
      contact: 'Contact',
      getQuote: 'Demander un devis',
      byMaterial: 'Par matériau',
      byApplication: 'Par application',
    },
    home: {
      heroTitle: 'Solutions en cuir synthétique premium',
      heroSubtitle: 'Fabricant professionnel de PU cuir, microfibre et matériaux spéciaux pour chaussures, sacs, automobile et gants',
      exploreProducts: 'Voir les produits',
      requestQuote: 'Demander un devis',
      ourProducts: 'Nos produits',
      productTitle: 'Matériaux en cuir premium',
      productDesc: 'Du PU cuir classique à la microfibre de pointe - nous avons le matériau parfait pour chaque application.',
      certifications: 'Assurance qualité',
      certTitle: 'Certifié & Fiable',
      certDesc: 'Tous les produits répondent aux normes internationales de qualité et de sécurité.',
      whyChooseUs: 'Pourquoi nous choisir',
      advantages: 'Nos avantages clés',
      advantagesDesc: 'Avec des capacités R&D professionnelles et un contrôle qualité rigoureux, nous offrons une valeur exceptionnelle.',
      learnMore: 'En savoir plus',
      readyToFind: 'Prêt à trouver le cuir parfait?',
      ctaDesc: 'Contactez notre équipe pour des échantillons gratuits, une consultation technique ou un devis personnalisé.',
      browseProducts: 'Parcourir les produits',
    },
    products: {
      title: 'Séries de produits',
      byMaterial: 'Par matériau',
      byMaterialDesc: 'Choisissez le matériau le mieux adapté à vos besoins.',
      byApplication: 'Par application',
      byApplicationDesc: 'Trouvez le matériau parfait pour votre secteur.',
      viewDetails: 'Voir les détails',
      downloadCatalog: 'Télécharger le catalogue',
      needCustom: 'Besoin d\'un matériau personnalisé?',
      needCustomDesc: 'Nous proposons des couleurs personnalisées, des ajustements d\'épaisseur et des finitions fonctionnelles.',
      requestSample: 'Demander un échantillon personnalisé',
    },
    productDetail: {
      backToProducts: 'Retour aux produits',
      productOverview: 'Aperçu du produit',
      composition: 'Composition',
      availableColors: 'Couleurs disponibles',
      applications: 'Applications',
      technicalSpecs: 'Spécifications techniques',
      downloadFullTDS: 'Télécharger TDS complet',
      fabricInfo: 'Info tissu',
      physical: 'Propriétés physiques',
      colorFastness: 'Solidité des couleurs',
      environmental: 'Environnement & Conformité',
      thickness: 'Épaisseur',
      width: 'Largeur',
      weight: 'Poids',
      moq: 'Commande minimum',
      requestQuote: 'Demander un devis',
      downloadSpec: 'Télécharger la fiche technique',
      inquiry: 'Demander un échantillon ou un devis',
      inquiryDesc: 'Partagez vos besoins et nous vous répondrons dans les 24 heures.',
      getInTouch: 'Contactez-nous',
      getInTouchDesc: 'Contactez notre équipe commerciale pour des échantillons, des spécifications personnalisées ou des devis détaillés.',
      freeSamples: 'Échantillons gratuits:',
      freeSamplesDesc: 'Nous proposons des échantillons A4 gratuits pour évaluation de la qualité.',
      sendInquiry: 'Envoyer une demande',
      sendInquiryDesc: 'Remplissez le formulaire ci-dessous et nous vous répondrons rapidement.',
    },
    inquiry: {
      company: 'Nom de l\'entreprise',
      contact: 'Personne de contact',
      phone: 'Téléphone',
      email: 'Email',
      product: 'Produit',
      thickness: 'Épaisseur',
      color: 'Couleur',
      usage: 'Utilisation',
      quantity: 'Quantité nécessaire',
      requirements: 'Exigences spéciales',
      message: 'Message',
      submit: 'Envoyer la demande',
      submitting: 'Envoi en cours...',
      success: 'Demande envoyée avec succès! Nous vous contacterons bientôt.',
      error: 'Échec de l\'envoi. Veuillez réessayer.',
    },
    about: {
      title: 'À propos',
      subtitle: 'Votre partenaire de confiance en cuir synthétique',
      story: 'Notre histoire',
      storyDesc: 'Fondée à Dongguan, en Chine, Ultra Leather est devenue un fabricant leader...',
      mission: 'Notre mission',
      missionDesc: 'Fournir des solutions en cuir synthétique innovantes et durables à nos clients mondiaux...',
      vision: 'Notre vision',
      visionDesc: 'Être le partenaire le plus fiable pour les matériaux en cuir synthétique dans le monde...',
      team: 'Notre équipe',
      capabilities: 'Nos capacités',
    },
    contact: {
      title: 'Contactez-nous',
      subtitle: 'Entrer en contact',
      name: 'Nom complet',
      email: 'Adresse email',
      subject: 'Sujet',
      message: 'Votre message',
      send: 'Envoyer le message',
      sending: 'Envoi en cours...',
      success: 'Message envoyé avec succès! Nous vous répondrons bientôt.',
      company: 'Nom de l\'entreprise',
      address: 'Adresse',
      phone: 'Téléphone',
      whatsapp: 'WhatsApp',
      hours: 'Heures d\'ouverture',
    },
    footer: {
      company: 'Ultra Leather',
      tagline: 'Solutions en cuir synthétique premium',
      products: 'Produits',
      company: 'Entreprise',
      contact: 'Contact',
      newsletter: 'Newsletter',
      newsletterDesc: 'Abonnez-vous pour les dernières mises à jour.',
      rights: 'Tous droits réservés.',
    },
    common: {
      loading: 'Chargement...',
      error: 'Erreur',
      retry: 'Réessayer',
      close: 'Fermer',
      save: 'Enregistrer',
      cancel: 'Annuler',
      delete: 'Supprimer',
      edit: 'Modifier',
      add: 'Ajouter',
      search: 'Rechercher',
      noResults: 'Aucun résultat',
      learnMore: 'En savoir plus',
      viewAll: 'Voir tout',
    },
  },
  de: {
    nav: {
      home: 'Startseite',
      products: 'Produkte',
      newArrivals: 'Neuheiten',
      applications: 'Anwendungen',
      about: 'Über uns',
      contact: 'Kontakt',
      getQuote: 'Angebot anfordern',
      byMaterial: 'Nach Material',
      byApplication: 'Nach Anwendung',
    },
    home: {
      heroTitle: 'Premium Kunstleder Lösungen',
      heroSubtitle: 'Professioneller Hersteller von PU-Leder, Mikrofaser und Spezialmaterialien für Schuhe, Taschen, Automobilinnenausstattung und Handschuhe',
      exploreProducts: 'Produkte ansehen',
      requestQuote: 'Angebot anfordern',
      ourProducts: 'Unsere Produkte',
      productTitle: 'Premium Lederalternativen',
      productDesc: 'Vom klassischen PU-Leder bis zu hochmoderner Mikrofaser - wir haben das perfekte Material für jede Anwendung.',
      certifications: 'Qualitätssicherung',
      certTitle: 'Zertifiziert & Vertrauenswürdig',
      certDesc: 'Alle Produkte erfüllen internationale Qualitäts- und Sicherheitsstandards.',
      whyChooseUs: 'Warum uns wählen',
      advantages: 'Unsere Kernvorteile',
      advantagesDesc: 'Mit professionellen F&E-Kapazitäten und strenger Qualitätskontrolle bieten wir außergewöhnlichen Wert.',
      learnMore: 'Mehr erfahren',
      readyToFind: 'Bereit, das perfekte Leder zu finden?',
      ctaDesc: 'Kontaktieren Sie unser Team für kostenlose Muster, technische Beratung oder individuelle Angebote.',
      browseProducts: 'Produkte durchsuchen',
    },
    products: {
      title: 'Produktserien',
      byMaterial: 'Nach Material',
      byMaterialDesc: 'Wählen Sie das Material, das am besten zu Ihren Produktanforderungen passt.',
      byApplication: 'Nach Anwendung',
      byApplicationDesc: 'Finden Sie das perfekte Material für Ihre spezifische Branche.',
      viewDetails: 'Details anzeigen',
      downloadCatalog: 'Katalog herunterladen',
      needCustom: 'Benötigen Sie ein individuelles Material?',
      needCustomDesc: 'Wir bieten kundenspezifische Farbanpassung, Dickenanpassung und Funktionsveredelungen.',
      requestSample: 'Individuelles Muster anfordern',
    },
    productDetail: {
      backToProducts: 'Zurück zu Produkten',
      productOverview: 'Produktübersicht',
      composition: 'Zusammensetzung',
      availableColors: 'Verfügbare Farben',
      applications: 'Anwendungen',
      technicalSpecs: 'Technische Spezifikationen',
      downloadFullTDS: 'Vollständiges TDS herunterladen',
      fabricInfo: 'Stoffinformationen',
      physical: 'Physikalische Eigenschaften',
      colorFastness: 'Farbechtheit',
      environmental: 'Umwelt & Konformität',
      thickness: 'Dicke',
      width: 'Breite',
      weight: 'Gewicht',
      moq: 'Mindestbestellmenge',
      requestQuote: 'Angebot anfordern',
      downloadSpec: 'Spezifikationsblatt herunterladen',
      inquiry: 'Muster oder Angebot anfordern',
      inquiryDesc: 'Teilen Sie uns Ihre Anforderungen mit, wir antworten innerhalb von 24 Stunden.',
      getInTouch: 'Kontaktieren Sie uns',
      getInTouchDesc: 'Kontaktieren Sie unser Vertriebsteam für Produktmuster, kundenspezifische Spezifikationen oder detaillierte Angebote.',
      freeSamples: 'Kostenlose Muster:',
      freeSamplesDesc: 'Wir bieten kostenlose A4-Muster zur Qualitätsbewertung an.',
      sendInquiry: 'Anfrage senden',
      sendInquiryDesc: 'Füllen Sie das Formular aus und wir melden uns schnellstmöglich.',
    },
    inquiry: {
      company: 'Firmenname',
      contact: 'Ansprechpartner',
      phone: 'Telefon',
      email: 'E-Mail',
      product: 'Produkt',
      thickness: 'Dicke',
      color: 'Farbe',
      usage: 'Verwendung',
      quantity: 'Benötigte Menge',
      requirements: 'Besondere Anforderungen',
      message: 'Nachricht',
      submit: 'Anfrage senden',
      submitting: 'Wird gesendet...',
      success: 'Anfrage erfolgreich gesendet! Wir werden Sie bald kontaktieren.',
      error: 'Senden fehlgeschlagen. Bitte versuchen Sie es erneut.',
    },
    about: {
      title: 'Über uns',
      subtitle: 'Ihr vertrauenswürdiger Partner für Kunstleder',
      story: 'Unsere Geschichte',
      storyDesc: 'Gegründet in Dongguan, China, hat sich Ultra Leather zu einem führenden Hersteller entwickelt...',
      mission: 'Unsere Mission',
      missionDesc: 'Unseren globalen Kunden innovative, nachhaltige und kosteneffiziente Kunstlederlösungen bieten...',
      vision: 'Unsere Vision',
      visionDesc: 'Der vertrauenswürdigste Partner für Kunstledermaterialien weltweit sein...',
      team: 'Unser Team',
      capabilities: 'Unsere Fähigkeiten',
    },
    contact: {
      title: 'Kontakt',
      subtitle: 'Verbinden Sie sich mit uns',
      name: 'Vollständiger Name',
      email: 'E-Mail-Adresse',
      subject: 'Betreff',
      message: 'Ihre Nachricht',
      send: 'Nachricht senden',
      sending: 'Wird gesendet...',
      success: 'Nachricht erfolgreich gesendet! Wir werden bald antworten.',
      company: 'Firmenname',
      address: 'Adresse',
      phone: 'Telefon',
      whatsapp: 'WhatsApp',
      hours: 'Geschäftszeiten',
    },
    footer: {
      company: 'Ultra Leather',
      tagline: 'Premium Kunstleder Lösungen',
      products: 'Produkte',
      company: 'Unternehmen',
      contact: 'Kontakt',
      newsletter: 'Newsletter',
      newsletterDesc: 'Abonnieren Sie für die neuesten Updates.',
      rights: 'Alle Rechte vorbehalten.',
    },
    common: {
      loading: 'Wird geladen...',
      error: 'Fehler',
      retry: 'Erneut versuchen',
      close: 'Schließen',
      save: 'Speichern',
      cancel: 'Abbrechen',
      delete: 'Löschen',
      edit: 'Bearbeiten',
      add: 'Hinzufügen',
      search: 'Suchen',
      noResults: 'Keine Ergebnisse gefunden',
      learnMore: 'Mehr erfahren',
      viewAll: 'Alle anzeigen',
    },
  },
  es: {
    nav: {
      home: 'Inicio',
      products: 'Productos',
      newArrivals: 'Novedades',
      applications: 'Aplicaciones',
      about: 'Nosotros',
      contact: 'Contacto',
      getQuote: 'Solicitar presupuesto',
      byMaterial: 'Por material',
      byApplication: 'Por aplicación',
    },
    home: {
      heroTitle: 'Soluciones de cuero sintético premium',
      heroSubtitle: 'Fabricante profesional de cuero PU, microfibra y materiales especiales para calzado, bolsos, automoción y guantes',
      exploreProducts: 'Ver productos',
      requestQuote: 'Solicitar presupuesto',
      ourProducts: 'Nuestros productos',
      productTitle: 'Materiales de cuero premium',
      productDesc: 'Desde el clásico cuero PU hasta la microfibra de vanguardia - tenemos el material perfecto para cada aplicación.',
      certifications: 'Garantía de calidad',
      certTitle: 'Certificado & Confiable',
      certDesc: 'Todos los productos cumplen con los estándares internacionales de calidad y seguridad.',
      whyChooseUs: 'Por qué elegirnos',
      advantages: 'Nuestras ventajas clave',
      advantagesDesc: 'Con capacidades profesionales de I+D y control de calidad estricto, ofrecemos valor excepcional.',
      learnMore: 'Saber más',
      readyToFind: '¿Listo para encontrar el cuero perfecto?',
      ctaDesc: 'Contáctenos para obtener muestras gratuitas, consultoría técnica o presupuestos personalizados.',
      browseProducts: 'Explorar productos',
    },
    products: {
      title: 'Series de productos',
      byMaterial: 'Por material',
      byMaterialDesc: 'Elija el material que mejor se adapte a los requisitos de su producto.',
      byApplication: 'Por aplicación',
      byApplicationDesc: 'Encuentre el material perfecto para su industria específica.',
      viewDetails: 'Ver detalles',
      downloadCatalog: 'Descargar catálogo',
      needCustom: '¿Necesita material personalizado?',
      needCustomDesc: 'Ofrecemos colores personalizados, ajuste de espesor y acabados funcionales.',
      requestSample: 'Solicitar muestra personalizada',
    },
    productDetail: {
      backToProducts: 'Volver a productos',
      productOverview: 'Descripción del producto',
      composition: 'Composición',
      availableColors: 'Colores disponibles',
      applications: 'Aplicaciones',
      technicalSpecs: 'Especificaciones técnicas',
      downloadFullTDS: 'Descargar TDS completo',
      fabricInfo: 'Info del tejido',
      physical: 'Propiedades físicas',
      colorFastness: 'Solidez del color',
      environmental: 'Medioambiente y cumplimiento',
      thickness: 'Espesor',
      width: 'Ancho',
      weight: 'Peso',
      moq: 'Cantidad mínima',
      requestQuote: 'Solicitar presupuesto',
      downloadSpec: 'Descargar ficha técnica',
      inquiry: 'Solicitar muestra o presupuesto',
      inquiryDesc: 'Cuéntenos sus requisitos y le responderemos en 24 horas.',
      getInTouch: 'Contáctenos',
      getInTouchDesc: 'Contacte a nuestro equipo de ventas para muestras, especificaciones personalizadas o presupuestos detallados.',
      freeSamples: 'Muestras gratuitas:',
      freeSamplesDesc: 'Ofrecemos muestras A4 gratuitas para evaluación de calidad.',
      sendInquiry: 'Enviar consulta',
      sendInquiryDesc: 'Complete el formulario y le responderemos pronto.',
    },
    inquiry: {
      company: 'Nombre de empresa',
      contact: 'Persona de contacto',
      phone: 'Teléfono',
      email: 'Correo electrónico',
      product: 'Producto',
      thickness: 'Espesor',
      color: 'Color',
      usage: 'Uso',
      quantity: 'Cantidad necesaria',
      requirements: 'Requisitos especiales',
      message: 'Mensaje',
      submit: 'Enviar consulta',
      submitting: 'Enviando...',
      success: '¡Consulta enviada con éxito! Le contactaremos pronto.',
      error: 'Error al enviar. Por favor, inténtelo de nuevo.',
    },
    about: {
      title: 'Sobre nosotros',
      subtitle: 'Su socio de confianza en cuero sintético',
      story: 'Nuestra historia',
      storyDesc: 'Fundada en Dongguan, China, Ultra Leather se ha convertido en un fabricante líder...',
      mission: 'Nuestra misión',
      missionDesc: 'Proporcionar soluciones innovadoras y sostenibles de cuero sintético a nuestros clientes globales...',
      vision: 'Nuestra visión',
      visionDesc: 'Ser el socio más confiable para materiales de cuero sintético en todo el mundo...',
      team: 'Nuestro equipo',
      capabilities: 'Nuestras capacidades',
    },
    contact: {
      title: 'Contáctenos',
      subtitle: 'Conéctese con nosotros',
      name: 'Nombre completo',
      email: 'Correo electrónico',
      subject: 'Asunto',
      message: 'Su mensaje',
      send: 'Enviar mensaje',
      sending: 'Enviando...',
      success: '¡Mensaje enviado con éxito! Le responderemos pronto.',
      company: 'Nombre de empresa',
      address: 'Dirección',
      phone: 'Teléfono',
      whatsapp: 'WhatsApp',
      hours: 'Horario de atención',
    },
    footer: {
      company: 'Ultra Leather',
      tagline: 'Soluciones de cuero sintético premium',
      products: 'Productos',
      company: 'Empresa',
      contact: 'Contacto',
      newsletter: 'Boletín',
      newsletterDesc: 'Suscríbase para recibir las últimas actualizaciones.',
      rights: 'Todos los derechos reservados.',
    },
    common: {
      loading: 'Cargando...',
      error: 'Error',
      retry: 'Reintentar',
      close: 'Cerrar',
      save: 'Guardar',
      cancel: 'Cancelar',
      delete: 'Eliminar',
      edit: 'Editar',
      add: 'Añadir',
      search: 'Buscar',
      noResults: 'Sin resultados',
      learnMore: 'Saber más',
      viewAll: 'Ver todo',
    },
  },
  ru: {
    nav: {
      home: 'Главная',
      products: 'Продукция',
      newArrivals: 'Новинки',
      applications: 'Применение',
      about: 'О компании',
      contact: 'Контакты',
      getQuote: 'Запросить цену',
      byMaterial: 'По материалу',
      byApplication: 'По применению',
    },
    home: {
      heroTitle: 'Премиум решения из искусственной кожи',
      heroSubtitle: 'Профессиональный производитель PU-кожи, микрофибры и специальных материалов для обуви, сумок, автомобильных интерьеров и перчаток',
      exploreProducts: 'Смотреть продукцию',
      requestQuote: 'Запросить цену',
      ourProducts: 'Наша продукция',
      productTitle: 'Премиум материалы из кожи',
      productDesc: 'От классической PU-кожи до современной микрофибры - у нас есть идеальный материал для любого применения.',
      certifications: 'Гарантия качества',
      certTitle: 'Сертифицировано и надёжно',
      certDesc: 'Вся продукция соответствует международным стандартам качества и безопасности.',
      whyChooseUs: 'Почему мы',
      advantages: 'Наши ключевые преимущества',
      advantagesDesc: 'Благодаря профессиональным возможностям НИОКР и строгому контролю качества мы предлагаем исключительную ценность.',
      learnMore: 'Узнать больше',
      readyToFind: 'Готовы найти идеальную кожу?',
      ctaDesc: 'Свяжитесь с нашей командой для получения бесплатных образцов, технической консультации или индивидуального предложения.',
      browseProducts: 'Просмотр продукции',
    },
    products: {
      title: 'Серии продукции',
      byMaterial: 'По материалу',
      byMaterialDesc: 'Выберите материал, наиболее соответствующий требованиям вашего продукта.',
      byApplication: 'По применению',
      byApplicationDesc: 'Найдите идеальный материал для вашей конкретной отрасли.',
      viewDetails: 'Подробнее',
      downloadCatalog: 'Скачать каталог',
      needCustom: 'Нужен индивидуальный материал?',
      needCustomDesc: 'Мы предлагаем индивидуальную колеровку, регулировку толщины и функциональную обработку.',
      requestSample: 'Запросить индивидуальный образец',
    },
    productDetail: {
      backToProducts: 'Вернуться к продукции',
      productOverview: 'Обзор продукта',
      composition: 'Состав',
      availableColors: 'Доступные цвета',
      applications: 'Применение',
      technicalSpecs: 'Технические характеристики',
      downloadFullTDS: 'Скачать полный TDS',
      fabricInfo: 'Информация о ткани',
      physical: 'Физические свойства',
      colorFastness: 'Стойкость цвета',
      environmental: 'Экология и соответствие',
      thickness: 'Толщина',
      width: 'Ширина',
      weight: 'Вес',
      moq: 'Минимальный заказ',
      requestQuote: 'Запросить цену',
      downloadSpec: 'Скачать спецификацию',
      inquiry: 'Запрос образца или цены',
      inquiryDesc: 'Расскажите о ваших требованиях, и мы ответим в течение 24 часов.',
      getInTouch: 'Свяжитесь с нами',
      getInTouchDesc: 'Свяжитесь с нашей командой продаж для получения образцов, индивидуальных спецификаций или подробных предложений.',
      freeSamples: 'Бесплатные образцы:',
      freeSamplesDesc: 'Мы предлагаем бесплатные образцы формата A4 для оценки качества.',
      sendInquiry: 'Отправить запрос',
      sendInquiryDesc: 'Заполните форму ниже, и мы свяжемся с вами в ближайшее время.',
    },
    inquiry: {
      company: 'Название компании',
      contact: 'Контактное лицо',
      phone: 'Телефон',
      email: 'Эл. почта',
      product: 'Продукт',
      thickness: 'Толщина',
      color: 'Цвет',
      usage: 'Применение',
      quantity: 'Требуемое количество',
      requirements: 'Особые требования',
      message: 'Сообщение',
      submit: 'Отправить запрос',
      submitting: 'Отправка...',
      success: 'Запрос успешно отправлен! Мы свяжемся с вами в ближайшее время.',
      error: 'Ошибка отправки. Пожалуйста, попробуйте ещё раз.',
    },
    about: {
      title: 'О компании',
      subtitle: 'Ваш надёжный партнёр в области искусственной кожи',
      story: 'Наша история',
      storyDesc: 'Основанная в Дунгуане, Китай, компания Ultra Leather стала ведущим производителем...',
      mission: 'Наша миссия',
      missionDesc: 'Предоставлять нашим глобальным клиентам инновационные, устойчивые и экономически эффективные решения из искусственной кожи...',
      vision: 'Наше видение',
      visionDesc: 'Стать самым надёжным партнёром в области материалов из искусственной кожи по всему миру...',
      team: 'Наша команда',
      capabilities: 'Наши возможности',
    },
    contact: {
      title: 'Контакты',
      subtitle: 'Свяжитесь с нами',
      name: 'Полное имя',
      email: 'Электронная почта',
      subject: 'Тема',
      message: 'Ваше сообщение',
      send: 'Отправить сообщение',
      sending: 'Отправка...',
      success: 'Сообщение успешно отправлено! Мы ответим в ближайшее время.',
      company: 'Название компании',
      address: 'Адрес',
      phone: 'Телефон',
      whatsapp: 'WhatsApp',
      hours: 'Часы работы',
    },
    footer: {
      company: 'Ultra Leather',
      tagline: 'Премиум решения из искусственной кожи',
      products: 'Продукция',
      company: 'Компания',
      contact: 'Контакт',
      newsletter: 'Рассылка',
      newsletterDesc: 'Подпишитесь на получение последних обновлений.',
      rights: 'Все права защищены.',
    },
    common: {
      loading: 'Загрузка...',
      error: 'Ошибка',
      retry: 'Повторить',
      close: 'Закрыть',
      save: 'Сохранить',
      cancel: 'Отмена',
      delete: 'Удалить',
      edit: 'Редактировать',
      add: 'Добавить',
      search: 'Поиск',
      noResults: 'Результатов не найдено',
      learnMore: 'Узнать больше',
      viewAll: 'Показать все',
    },
  },
}

// Language Context
const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en')
  const [isReady, setIsReady] = useState(false)

  useEffect(() => {
    // 检测浏览器语言
    const savedLang = localStorage.getItem('ultrapu-lang')
    if (savedLang && translations[savedLang]) {
      setLang(savedLang)
    } else {
      const browserLang = navigator.language.split('-')[0]
      if (translations[browserLang]) {
        setLang(browserLang)
      } else if (navigator.language.startsWith('zh')) {
        setLang('zh')
      }
    }
    setIsReady(true)
  }, [])

  const changeLanguage = (newLang) => {
    if (translations[newLang]) {
      setLang(newLang)
      localStorage.setItem('ultrapu-lang', newLang)
      // 更新页面方向 (RTL)
      const langInfo = languages.find(l => l.code === newLang)
      document.documentElement.dir = langInfo?.rtl ? 'rtl' : 'ltr'
    }
  }

  const t = (key) => {
    const keys = key.split('.')
    let value = translations[lang]
    for (const k of keys) {
      value = value?.[k]
    }
    return value || translations['en']?.[key] || key
  }

  const currentLangInfo = languages.find(l => l.code === lang) || languages[0]

  const value = {
    lang,
    setLang: changeLanguage,
    t,
    languages,
    currentLangInfo,
    isReady,
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
